### ISSUE TITLE
Clean up POST dossier endpoint

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stixify#36]
![image](https://github.com/user-attachments/assets/3f258a5d-783c-4026-b3f6-b6b20397db8f)

Dossier should have

`report_ids` (array): `id`s of Report objects you want to add to dossier
`name`: name of the dossier
`description`: description of the dossier
`created_by_ref` (valid stix identity object json): assigned as owner of dossier
`tlp_level` (use STIX2 TLP levels -- same as files): tlp level of dossier
`labels` (array of alphanumeric chars): labels to be attached to dossier

**Comment by fqrious** [comment]
You asked me to remove tlp_level in #18, should I really add it back?

**Comment by himynamesdave** [comment]
@fqrious i am designing Stixify web, and realised its needed. Sorry to make you go back and do this, but yes, needed
