### ISSUE TITLE
Add DELETE Report endpoint

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stixify#54]
(we did have this previously, but based on actual usage have realised we still need it)

This should delete all SROs and SDOs for the report

It should not delete any SCOs. This is important. Because we dump all reports in one arango bucket, it is possible other reports have the same SCOs, thus SCOS should remain, else it will break relationships with remaining reports.

**Comment by himynamesdave** [comment]
Need to add summary and description

Should read

Delete a Report by ID

This endpoint will delete a Report using its ID. It will also delete all SDOs and SROs created when extractions were made for this Report.

IMPORTANT: this request does NOT delete the File this Report was created from. Use the DELETE File by ID endpoint to delete the File. This request does NOT delete any SCOs created by extractions from this report because they could be linked to other Reports.

**Comment by fqrious** [comment]
> This request does NOT delete any SCOs created by extractions from this report because they could be linked to other Reports.

So what happend when someone deletes and then they upload another file with same report_id?

**Comment by himynamesdave** [comment]
Well SCOs are generated using the value and the OASIS namespace

Thus the SCOs will always have the same ID regardless of the report. Thus in your example, stix2arango attempts to create a new SCO, does not change it b/c no update, but new SDO linked to existing SCO.

Is that what you were asking?

**Comment by fqrious** [comment]
because of how the upload works, the old SCOs are still there pointing to a non-existent report. Now, if I upload a new file that only contains one SCO, filtering for that report will return the old old objects as well as the new objects

**Comment by himynamesdave** [comment]
how exactly does a SCO belong to a report in the database?

I understand you point, but what in the SCO object record is pointing to a Report ID?

**Comment by fqrious** [comment]
`_stixify_report_id`

**Comment by himynamesdave** [comment]
Discussed here

https://dogesec.slack.com/archives/D05L8JEAM1N/p1730474596676819

Seems we need to ignore is latest when returning SCO results to user in search

BUT this does mean we can DELETE the SCO in this request

**Comment by fqrious** [comment]
should removing a report also remove the associated file? What about removing a file?

**Comment by himynamesdave** [comment]
Need to add summary / description

https://github.com/muchdogesec/stixify/issues/54#issuecomment-2451430089

**Comment by himynamesdave** [comment]
@fqrious delete works, but should accept stix report id to be consistent with other endpoints

![Image](https://github.com/user-attachments/assets/eb850f8a-5fd6-443c-a34c-0f3bd00d4850)

**Comment by fqrious** [comment]
it'll work with or without `report--` prefix
