### ISSUE TITLE
R2 path incorrect

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stixify#55]
![Cloudflare-Web-Performance-Security-10-30-2024_02_08_PM](https://github.com/user-attachments/assets/ef8c9df2-daf3-4dea-9ab6-cc4db08d86ac)

Remove `stixify/media` from the path. Idea is that the bucket will represent stixify, so just print file `ids`/ at top level

**Comment by fqrious** [comment]
`/media/` and `/staticfiles/` are going to be on r2. But I'll remove the `stixify` prefix
