### ISSUE TITLE
Modify R2 storage logic

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stixify#83]
![image](https://github.com/user-attachments/assets/c30ebd71-2493-45b0-9421-9b90306a5b31)
 
 We should only upload file data (currently django static assets are also included)
 
Store in structure

`files/<identity ID/<report ID>/`

Inside stores the original file, the markdown conversion, and any images extracted from the doc.

**Comment by fqrious** [comment]
django files have to be uploaded somewhere, django does not host files in production.

**Comment by himynamesdave** [comment]
@fqrious ok can we use the paths

`files/<identity ID/<report ID>/`
`django/staticfiles/...`

?
